server:
  port: 8000
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.137.128:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    port: 6379
    host: 192.168.137.128
mybatis:
  mapper-locations: classpath*:cn/mapper/*.xml
logging:
  level:
    com.lk.mybatis.dao: debug
